### ISSUE TITLE
# Localization - ![国语][TW] Taiwanese (国语) <zh-tw.cfg>

### ISSUE THREAD

**Issue by chillfun420** [chillfun420/HelloWorld#2]
# Localization - ![国语][TW] Taiwanese (国语) <zh-tw.cfg>

## GitHub

* [X] assign
  * [X] zer0Kerbal
  * [X] Repo Localization Project
  * [X] Label: type: localization
  * [X] Label: help-wanted
  * [X] Milestone: Localization - Master

### GameData

* [x] add  Localization\[zh-tw.cfg] 🗃️

### Translation

* [x] ![国语][TW] Taiwanese (国语) <zh-tw.cfg>

### Documentation

* [x] Update [readme.md] 🔢
* [x] Update [release.md] 🧾

### Wiki

* [x] Update docs/[localization.md]

## Update Social Media

* [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
* [x] CurseForge
* [x] Reddit
* [x] Twitter @zer0Kerbal
* [x] Forum
* [x] Patreon
* [x] SpaceDock
* [x] CKAN (automated)

[lclztn]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/readme.md 
[qs]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/quickstart.md

[TW]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/master/img/TW.png

__Originally posted by @zer0Kerbal in https://github.com/zer0Kerbal/InflatablePicoPorts/issues/23__

__Originally posted by @chillfun420 in https://github.com/chillfun420/HelloWorld/issues/1__

**Comment by chillfun420** [comment]
> # Localization - ![国语][TW] Taiwanese (国语) <zh-tw.cfg>
> 
> 
> 
> ## GitHub
> 
> 
> 
> * [X] assign
> 
>   * [X] zer0Kerbal
> 
>   * [X] Repo Localization Project
> 
>   * [X] Label: type: localization
> 
>   * [X] Label: help-wanted
> 
>   * [X] Milestone: Localization - Master
> 
> 
> 
> ### GameData
> 
> 
> 
> * [x] add  Localization\[zh-tw.cfg] 🗃️
> 
> 
> 
> ### Translation
> 
> 
> 
> * [x] ![国语][TW] Taiwanese (国语) <zh-tw.cfg>
> 
> 
> 
> ### Documentation
> 
> 
> 
> * [x] Update [readme.md] 🔢
> 
> * [x] Update [release.md] 🧾
> 
> 
> 
> ### Wiki
> 
> 
> 
> * [x] Update docs/[localization.md]
> 
> 
> 
> ## Update Social Media
> 
> 
> 
> * [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
> 
> * [x] CurseForge
> 
> * [x] Reddit
> 
> * [x] Twitter @zer0Kerbal
> 
> * [x] Forum
> 
> * [x] Patreon
> 
> * [x] SpaceDock
> 
> * [x] CKAN (automated)
> 
> 
> 
> 
> 
> [lclztn]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/readme.md 
> 
> [qs]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/quickstart.md
> 
> 
> 
> [TW]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/master/img/TW.png
> 
> 
> 
> 
> 
> 
> 
> __Originally posted by @zer0Kerbal in https://github.com/zer0Kerbal/InflatablePicoPorts/issues/23__
> 
> __Originally posted by @chillfun420 in https://github.com/chillfun420/HelloWorld/issues/1__

**Comment by zer0Kerbal** [comment]
@chillfun420 this file (the above) is licensed CC BY-***ND*** 4.0.

**Comment by zer0Kerbal** [comment]
NoDerivatives  https://creativecommons.org/licenses/by-nd/4.0/

**Comment by zer0Kerbal** [comment]
if you are intending to translate, just kindly fork the original repo.
